let Trigger = {
    初始化(){
        属性触发器挂载();
    }
}
function 属性触发器挂载(){
    触发中心.触发时('age',(val)=>{
        添加词条(`<span style="color:gray;font-size:12px">年龄:${val}</span>`,true);
    })
    触发中心.触发时('health',()=>{
        界面.更新();
    })
    触发中心.触发时('年龄段',(val)=>{
        if(val=='幼童'){
            if(属性.家境<=3){
                载入词库('贫穷幼童');
            }else{
                载入词库('幼童');
            }
        }else{
            卸载词库('幼童');
            卸载词库('贫穷幼童');
        }
    })
    触发中心.触发时('年龄段',(val)=>{
        if(val=='少年'){
            载入词库('少年');
        }else{
            卸载词库('少年');
        }
    })
    触发中心.触发时('年龄段',(val)=>{
        if(val=='中年'){
        }else{
        }
    })
    触发中心.触发时('年龄段',(val)=>{
        if(val=='青年'){
            载入词库('青年');
        }else{
            卸载词库('青年');
        }
    })
    触发中心.触发时('isWork',(val)=>{
        if(属性.isWork == undefined || 属性.isStudent) return;
        if(val){
            载入词库('社畜');
        }else{
            卸载词库('社畜');
        }
    })
    触发中心.触发时('isMarried',(val)=>{
        if(val){
            载入词库('结婚');
        }else{
            卸载词库('结婚');
        }
    })
    触发中心.触发时('isStudent',(val)=>{
        if(val){
            if(属性.家境<= 3){
                载入词库('农村学校');
            }else{
                载入词库('贵族学校');
            }
        }else{
            卸载词库('学校');
        }
    })
    触发中心.触发时('hasChild',(val)=>{
        if(val){
            载入词库('带娃');
        }else{
            卸载词库('带娃');
        }
    })
}

export default Trigger;